# Generated by Django 4.2.27 on 2026-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('ranking_data', models.JSONField(help_text='Stores the Top 10 JSON array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('date', 'timeframe')},
            },
        ),
        migrations.DeleteModel(
            name='DailyRanking',
        ),
    ]
