# Generated by Django 4.2.27 on 2026-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ranking_delete_dailyranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComebackData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('data', models.JSONField(help_text='Stores the full JSON response from Kpopping API')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comeback Data',
                'unique_together': {('year', 'month')},
            },
        ),
    ]
