# Generated by Django 4.2.27 on 2026-03-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comebackdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='timeframe',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('soloists', 'Solo Artists'), ('groups', 'Idol Groups')], default='daily', max_length=20),
        ),
    ]
