# Generated by Django 4.2.27 on 2026-03-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ranking_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('group_type', models.CharField(choices=[('BOY', 'Boy Group'), ('GIRL', 'Girl Group'), ('SOLO', 'Soloist')], max_length=10)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('logo_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
