# Generated by Django 4.2.27 on 2026-03-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kpopgroup_description_kpopgroup_image_url_kpopmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('source_title', models.CharField(max_length=300)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('body_html', models.TextField()),
                ('reading_time', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
