# Generated by Django 4.2.27 on 2026-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blog_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='image_2',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
