# Generated by Django 4.2.27 on 2026-03-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blog_article_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='image_3',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
