# Generated by Django 4.2.27 on 2026-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_fanclubmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('song_game', 'Song Game'), ('idol_scramble', 'Idol Scramble'), ('lyric_drop', 'Lyric Drop'), ('chart_clash', 'Chart Clash')], default='song_game', max_length=50),
        ),
    ]
