# Generated by Django 4.2.27 on 2026-03-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanclubmembership',
            name='is_genesis',
            field=models.BooleanField(default=False),
        ),
    ]
