# Generated by Django 4.2.27 on 2026-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fanclubmembership_is_genesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreLaunchSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-signed_up_at'],
            },
        ),
    ]
