# Generated by Django 4.2.27 on 2026-03-14 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_blogarticle_social_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('artist', models.CharField(max_length=200)),
                ('album_art', models.URLField(blank=True, max_length=500)),
                ('duration', models.CharField(default='3:00', help_text='e.g. 3:45', max_length=20)),
                ('is_request', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadioStationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_next', models.JSONField(default=list, help_text='List of RadioTrack IDs in queue order')),
                ('recently_played', models.JSONField(default=list, help_text='List of RadioTrack IDs in history order')),
                ('listeners_count', models.IntegerField(default=3847)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_as_state', to='core.radiotrack')),
            ],
            options={
                'verbose_name_plural': 'Radio Station State',
            },
        ),
    ]
