# Generated by Django 4.2.27 on 2026-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_radiotrack_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostationstate',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Time when the current track started playing', null=True),
        ),
    ]
