# Generated by Django 4.2.27 on 2026-03-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_radiostationstate_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiotrack',
            name='duration_seconds',
            field=models.IntegerField(default=180, help_text='Duration in seconds'),
        ),
    ]
