# Generated by Django 4.2.27 on 2026-03-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_radiotrack_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadioSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('host', models.CharField(default='Auto DJ', max_length=255)),
                ('genre', models.CharField(default='MUSIC', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.radioplaylist')),
            ],
            options={
                'verbose_name_plural': 'Radio Schedules',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='RadioPlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.radioplaylist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.radiotrack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='radioplaylist',
            name='tracks',
            field=models.ManyToManyField(related_name='playlists', through='core.RadioPlaylistTrack', to='core.radiotrack'),
        ),
    ]
