# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_radioplaylist_radioschedule_radioplaylisttrack_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadioScheduleTemplateSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('host', models.CharField(default='Auto DJ', max_length=255)),
                ('genre', models.CharField(default='MUSIC', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.radioplaylist')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.radioscheduletemplate')),
            ],
            options={
                'ordering': ['order', 'start_time'],
            },
        ),
    ]
