# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_radioscheduletemplate_and_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioscheduletemplateslot',
            name='show_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
