# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_radioscheduletemplateslot_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioschedule',
            name='show_color',
            field=models.CharField(default='CYAN', max_length=20),
        ),
        migrations.AddField(
            model_name='radioscheduletemplateslot',
            name='show_color',
            field=models.CharField(default='CYAN', max_length=20),
        ),
    ]
