# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_voice_over_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioplaylisttrack',
            name='duck_volume_percent',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='radioplaylisttrack',
            name='voice_over_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='radioplaylisttrack',
            name='voice_over_text',
            field=models.TextField(blank=True),
        ),
    ]
