# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_playlisttrack_voiceover_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioplaylisttrack',
            name='voice_over_start_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
