# Generated by Django 4.2.27 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_playlist_voice_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioplaylisttrack',
            name='duck_volume_percent',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
