# Generated by Django 4.2.27 on 2026-03-18 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_userprofile_digest_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBadgeDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=255)),
                ('badge_type', models.CharField(default='EVENT', max_length=50)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=20)),
                ('minimum_tier', models.CharField(choices=[('FREE', 'Free'), ('PLUS', 'Plus'), ('ULTRA', 'Ultra')], default='FREE', max_length=10)),
                ('min_votes_required', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes_cast', models.PositiveIntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='LimitedTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('event_type', models.CharField(choices=[('CHART_BATTLE', 'Chart Battle'), ('ARTIST_SPOTLIGHT', 'Artist Spotlight Week'), ('BADGE_DROP', 'Badge Drop')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.AddField(
            model_name='fanclubmembership',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PLUS', 'Plus'), ('ULTRA', 'Ultra')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='livepoll',
            name='early_access_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='early_access_polls', to='core.kpopgroup'),
        ),
        migrations.AddField(
            model_name='livepoll',
            name='early_access_min_tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('PLUS', 'Plus'), ('ULTRA', 'Ultra')], default='PLUS', max_length=10),
        ),
        migrations.AddField(
            model_name='livepoll',
            name='early_access_starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core.limitedtimeevent'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventbadgedrop',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_drops', to='core.limitedtimeevent'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipation',
            unique_together={('user', 'event')},
        ),
    ]
