# Generated by Django 4.2.27 on 2026-03-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_eventbadgedrop_eventparticipation_limitedtimeevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPromotionSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(default='homepage_newsletter', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='radiotrackplay',
            new_name='core_radiot_user_id_b4b3f7_idx',
            old_name='core_radiot_user_id_63c6b3_idx',
        ),
        migrations.RenameIndex(
            model_name='radiotrackplay',
            new_name='core_radiot_track_i_afef3b_idx',
            old_name='core_radiot_track_i_8a13c0_idx',
        ),
    ]
