# Generated by Django 4.2.27 on 2026-04-11 10:52

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def backfill_member_slugs(apps, schema_editor):
    KPopMember = apps.get_model('core', 'KPopMember')

    for member in KPopMember.objects.select_related('group').order_by('group_id', 'id'):
        base_slug = slugify(member.stage_name or member.name or member.full_name or '')[:120] or f"member-{member.id}"
        slug = base_slug
        suffix = 2
        while KPopMember.objects.exclude(pk=member.pk).filter(group_id=member.group_id, slug=slug).exists():
            slug = f"{base_slug[:110]}-{suffix}"
            suffix += 1
        member.slug = slug
        member.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_blogarticle_facebook_reel_preview_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpopgroup',
            name='agency',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kpopgroup',
            name='debut_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpopgroup',
            name='fandom_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kpopgroup',
            name='fandom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kpopgroup',
            name='group_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpopgroup',
            name='official_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='birthplace',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='debut_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='fan_facts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='korean_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='mbti',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='official_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='positions',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='profile_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='seo_description_override',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='kpopmember',
            name='slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.RunPython(backfill_member_slugs, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='kpopmember',
            unique_together={('group', 'slug')},
        ),
        migrations.CreateModel(
            name='MemberMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('milestone_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('birthday', 'Birthday'), ('career', 'Career'), ('release', 'Release'), ('editorial', 'Editorial')], default='career', max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.kpopmember')),
            ],
            options={
                'ordering': ['sort_order', '-milestone_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('embed_url', models.URLField(blank=True, max_length=500)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_features', to='core.kpopmember')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
