# Generated by Django 4.2.27 on 2026-07-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_blogarticle_writer_slug_and_editorial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='writer_slug',
            field=models.CharField(choices=[('mia-kang', 'Mia Kang'), ('sunny-park', 'Sunny Elliot'), ('james-elliott', 'James Park')], default='mia-kang', max_length=40),
        ),
    ]
