# Generated by Django 4.2.27 on 2026-07-15 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0051_alter_blogarticle_writer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('song_game', 'Song Game'), ('idol_scramble', 'Idol Scramble'), ('lyric_drop', 'Lyric Drop'), ('chart_clash', 'Chart Clash'), ('daily_drop', 'Daily Drop'), ('chart_oracle', 'Chart Oracle')], default='song_game', max_length=50),
        ),
        migrations.CreateModel(
            name='ChartPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(help_text='Date of the daily ranking the prediction was made against')),
                ('payload', models.JSONField(blank=True, default=dict, help_text="Matchups, the user's picks, and the #1 call")),
                ('resolved', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-prediction_date'],
                'unique_together': {('user', 'prediction_date')},
            },
        ),
    ]
