"""
Django settings for ksync_project project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*47mzio8v)0b=h0ue_bygkv@lm0=q4)%z7vir_+)r!e4h@y134'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # Relaxed for Heroku, adjust for production safety if needed


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'core.middleware.PreLaunchMiddleware',              # UNLOCKED
    'core.middleware.GoogleTagManagerMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ksync_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.seo_defaults',
            ],
        },
    },
]

WSGI_APPLICATION = 'ksync_project.wsgi.application'


# Database configuration - Using Neon PostgreSQL
# Defaulting to the provided Neon URL, but allowing override via DATABASE_URL env var
DEFAULT_DB_URL = 'postgresql://neondb_owner:npg_7BEvOGSUZY8R@ep-little-credit-aggzf1v2.c-2.eu-central-1.aws.neon.tech/stage_ditzy_error_436329'
USE_SQLITE_LOCAL = config('DJANGO_USE_SQLITE', default=False, cast=bool)

if USE_SQLITE_LOCAL:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL', DEFAULT_DB_URL),
            conn_max_age=60,
        )
    }

    # Enable health checks so Django will verify connections before using them.
    # Some versions of dj_database_url do not support conn_health_checks directly.
    DATABASES['default']['CONN_HEALTH_CHECKS'] = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user-uploaded / generated images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Auth
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Simplified static file storage as handled by Whitenoise.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── AI API Keys ──────────────────────────────────────────────────────────────
# In Heroku, add these via: heroku config:set DEEPSEEK_API_KEY=...
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', 'sk-16a74707578d4d589f9fb72db4954176')
INWORLD_API_KEY = os.environ.get('INWORLD_API_KEY', 'bnJvOURJZVdBV3VvRThMZVZKV085UlU0b2NPRDd0QTE6S2JzdTdvQ2FBRVBDOFNLTDl5dzFQT3JlWDJpekhibnNnMDNqWGU5VkNaQjhRdjM5bWIxQVZ4ejlQRGFBWUU3Zw==')
INWORLD_API_ROOT = os.environ.get('INWORLD_API_ROOT', 'https://api.inworld.ai')
INWORLD_BASE_URL = os.environ.get('INWORLD_BASE_URL', 'https://api.inworld.ai/v1')
INWORLD_CHAT_MODEL = os.environ.get('INWORLD_CHAT_MODEL', 'auto')
INWORLD_TTS_MODEL = os.environ.get('INWORLD_TTS_MODEL', 'inworld-tts-1.5-max')
GETIMG_API_KEY = os.environ.get('GETIMG_API_KEY', 'key-3t583MrYM5GrTQMJuymWSCOlQkylmA90xhvX7KB7eVRXgq24GwLXDHSYCVMqCDEBrTdYQn5n5MTVguY9tsFI8ZbQM4T4dbQ2')
# Free stock photos for blog articles — get a free key at pexels.com/api
PEXELS_API_KEY = os.environ.get('PEXELS_API_KEY', 'GPlKuBUuXNxu06VvSJIM4pCSUGtHBwp3NwT7Q0XfFWgL2dwGB7yMTRqP')
# Serper.dev — Google image search for blog articles (2,500 free/month)
SERPER_API_KEY = os.environ.get('SERPER_API_KEY', 'f099f725535455f20dd5a70ca6f817ddc3dc76e5')

# ── Facebook Page integration ────────────────────────────────────────────────
# ── Site URL ─────────────────────────────────────────────────────────────────
SITE_URL = os.environ.get('SITE_URL', 'https://kbeatsradio.co.uk')
GOOGLE_TAG_MANAGER_ID = os.environ.get('GOOGLE_TAG_MANAGER_ID', 'GTM-KDMN68PM')
ENABLE_THIRD_PARTY_TRACKING = os.environ.get(
    'ENABLE_THIRD_PARTY_TRACKING',
    'false' if DEBUG else 'true'
).lower() == 'true'

# ── Facebook ─────────────────────────────────────────────────────────────────
# Required permissions: pages_manage_posts, pages_read_engagement
FACEBOOK_PAGE_ID = os.environ.get('FACEBOOK_PAGE_ID', '966171646586881')
FACEBOOK_PAGE_ACCESS_TOKEN = os.environ.get('FACEBOOK_PAGE_ACCESS_TOKEN', 'EAAUVcMgjdSoBRLNnSM6y3lyzmuQoO1bMRMFrJ1ZAm0PZA7SpbnF9sURoQLVXXZA6CErrNX4xU9pSWtobwIGE08BeIdp06ZA1Ishh8aM6bD2BQ0HHZCp8MeZBN1oSiPcRJ5anJCFqPCglE0sPgK6SUsEA27i9usOnPZCezZB6LpyFnLOBPVqec8BNTnURreBtZAmr2h7KW9YUHlYQJkPq9PxmUysq4WC6c79N3rQv3WErlC0dtwZB2IurcoT7gmjs1vSTinBZBsNkNKjBeaD')
FACEBOOK_PIXEL_ID = os.environ.get('FACEBOOK_PIXEL_ID', '1694492738408843').strip()
FACEBOOK_HOMEPAGE_COMMENT_ENABLED = os.environ.get('FACEBOOK_HOMEPAGE_COMMENT_ENABLED', 'true').lower() == 'true'
FACEBOOK_HOMEPAGE_COMMENT_TEXT = os.environ.get('FACEBOOK_HOMEPAGE_COMMENT_TEXT', SITE_URL.rstrip('/') + '/')

# ── Instagram ─────────────────────────────────────────────────────────────────
# Instagram Business account must be linked to your Facebook Page.
# Uses the same Facebook Page Access Token above — no extra token needed.
# Set INSTAGRAM_POST_ENABLED=true to activate.
INSTAGRAM_POST_ENABLED = os.environ.get('INSTAGRAM_POST_ENABLED', 'false').lower() == 'true'

# ── X (Twitter) ───────────────────────────────────────────────────────────────
# Get from developer.twitter.com → Your App → Keys and Tokens
# Needs "Read and Write" OAuth 1.0a permissions.
X_POST_ENABLED = os.environ.get('X_POST_ENABLED', 'false').lower() == 'true'
X_POST_ON_CREATE_ENABLED = os.environ.get('X_POST_ON_CREATE_ENABLED', 'false').lower() == 'true'
X_POST_INTERVAL_MINUTES = int(os.environ.get('X_POST_INTERVAL_MINUTES', '40'))
X_API_KEY = os.environ.get('X_API_KEY', '')
X_API_SECRET = os.environ.get('X_API_SECRET', '')
X_ACCESS_TOKEN = os.environ.get('X_ACCESS_TOKEN', '')
X_ACCESS_TOKEN_SECRET = os.environ.get('X_ACCESS_TOKEN_SECRET', '')

# ── Pinterest ─────────────────────────────────────────────────────────────────
# Get from developers.pinterest.com → My Apps → your app → Access Token
# Board ID: open a board on Pinterest, copy the number from the URL.
PINTEREST_ACCESS_TOKEN = os.environ.get('PINTEREST_ACCESS_TOKEN', '')
PINTEREST_BOARD_ID = os.environ.get('PINTEREST_BOARD_ID', '')

# ── Cloudinary (image CDN) ───────────────────────────────────────────────────
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='diuanqnce')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='285831974678743')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

# ── Backblaze B2 (Audio Storage) ─────────────────────────────────────────────
B2_KEY_ID = os.environ.get('B2_KEY_ID', 'a2e0a74c71c2')
B2_APPLICATION_KEY = os.environ.get('B2_APPLICATION_KEY', '003309a8127932d4a086f5baf502ea6cada23f462d')
B2_BUCKET_NAME = os.environ.get('B2_BUCKET_NAME', 'StrayKids')
B2_DOWNLOAD_URL = os.environ.get('B2_DOWNLOAD_URL', 'https://f003.backblazeb2.com')

# Auto-sync radio library from Backblaze without manual runs.
# Keep this off by default in local DEBUG mode so `runserver` doesn't perform
# network syncs and mutate the radio library during normal development.
B2_AUTO_SYNC_ENABLED = str(config('B2_AUTO_SYNC_ENABLED', default='false' if DEBUG else 'true')).lower() == 'true'
B2_AUTO_SYNC_INTERVAL_MINUTES = int(config('B2_AUTO_SYNC_INTERVAL_MINUTES', default='30'))
B2_AUTO_SYNC_RUN_ON_STARTUP = str(config('B2_AUTO_SYNC_RUN_ON_STARTUP', default='false' if DEBUG else 'true')).lower() == 'true'
B2_AUTO_SYNC_NEW_ONLY = str(config('B2_AUTO_SYNC_NEW_ONLY', default='true')).lower() == 'true'
B2_AUTO_SYNC_PRUNE_MISSING = str(config('B2_AUTO_SYNC_PRUNE_MISSING', default='false')).lower() == 'true'
B2_AUTO_SYNC_INCLUDE_VERSIONS = str(config('B2_AUTO_SYNC_INCLUDE_VERSIONS', default='false')).lower() == 'true'

# Shuffle playlist order once per week (keeps song+VO pairs together)
PLAYLIST_WEEKLY_RANDOMIZE_ENABLED = os.environ.get('PLAYLIST_WEEKLY_RANDOMIZE_ENABLED', 'true').lower() == 'true'

# ── Audio delivery optimisation (Cloudinary Fetch in front of B2) ───────────
# Set to false to instantly revert to direct Backblaze URLs.
AUDIO_STREAM_USE_CLOUDINARY_FETCH = os.environ.get('AUDIO_STREAM_USE_CLOUDINARY_FETCH', 'false').lower() == 'true'
# Cloudinary video transformations are used for audio resources as well.
AUDIO_STREAM_CLOUDINARY_TRANSFORM = os.environ.get('AUDIO_STREAM_CLOUDINARY_TRANSFORM', 'q_auto:eco,br_96k,f_mp3')

# ── Image delivery optimisation (Cloudinary Fetch in front of B2) ───────────
# Set to true to rewrite Backblaze image URLs through Cloudinary image/fetch.
IMAGE_STREAM_USE_CLOUDINARY_FETCH = os.environ.get('IMAGE_STREAM_USE_CLOUDINARY_FETCH', 'false').lower() == 'true'
# Typical safe default for web images.
IMAGE_STREAM_CLOUDINARY_TRANSFORM = os.environ.get('IMAGE_STREAM_CLOUDINARY_TRANSFORM', 'f_auto,q_auto')

# ── Weekly image integrity checks ─────────────────────────────────────────────
IMAGE_INTEGRITY_CHECK_ENABLED = os.environ.get('IMAGE_INTEGRITY_CHECK_ENABLED', 'true').lower() == 'true'
IMAGE_INTEGRITY_CHECK_DAY_OF_WEEK = os.environ.get('IMAGE_INTEGRITY_CHECK_DAY_OF_WEEK', 'sun')
IMAGE_INTEGRITY_CHECK_HOUR = int(os.environ.get('IMAGE_INTEGRITY_CHECK_HOUR', '3'))
IMAGE_INTEGRITY_CHECK_MINUTE = int(os.environ.get('IMAGE_INTEGRITY_CHECK_MINUTE', '15'))
IMAGE_INTEGRITY_CHECK_LIMIT = int(os.environ.get('IMAGE_INTEGRITY_CHECK_LIMIT', '0'))
IMAGE_INTEGRITY_CHECK_TIMEOUT_SECONDS = float(os.environ.get('IMAGE_INTEGRITY_CHECK_TIMEOUT_SECONDS', '15'))
