"""
Django settings for ksync_project project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*47mzio8v)0b=h0ue_bygkv@lm0=q4)%z7vir_+)r!e4h@y134'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*'] # Relaxed for Heroku, adjust for production safety if needed


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'core.middleware.PreLaunchMiddleware',              # UNLOCKED
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ksync_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ksync_project.wsgi.application'


# Database configuration - Using Neon PostgreSQL
# Defaulting to the provided Neon URL, but allowing override via DATABASE_URL env var
DEFAULT_DB_URL = 'postgresql://neondb_owner:npg_7BEvOGSUZY8R@ep-little-credit-aggzf1v2.c-2.eu-central-1.aws.neon.tech/stage_ditzy_error_436329'

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', DEFAULT_DB_URL),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user-uploaded / generated images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Auth
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# Simplified static file storage as handled by Whitenoise.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── AI API Keys ──────────────────────────────────────────────────────────────
# In Heroku, add these via: heroku config:set DEEPSEEK_API_KEY=...
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY', 'sk-16a74707578d4d589f9fb72db4954176')
INWORLD_API_KEY = os.environ.get('INWORLD_API_KEY', 'bnJvOURJZVdBV3VvRThMZVZKV085UlU0b2NPRDd0QTE6S2JzdTdvQ2FBRVBDOFNLTDl5dzFQT3JlWDJpekhibnNnMDNqWGU5VkNaQjhRdjM5bWIxQVZ4ejlQRGFBWUU3Zw==')
INWORLD_API_ROOT = os.environ.get('INWORLD_API_ROOT', 'https://api.inworld.ai')
INWORLD_BASE_URL = os.environ.get('INWORLD_BASE_URL', 'https://api.inworld.ai/v1')
INWORLD_CHAT_MODEL = os.environ.get('INWORLD_CHAT_MODEL', 'auto')
INWORLD_TTS_MODEL = os.environ.get('INWORLD_TTS_MODEL', 'inworld-tts-1.5-max')
GETIMG_API_KEY = os.environ.get('GETIMG_API_KEY', 'key-3t583MrYM5GrTQMJuymWSCOlQkylmA90xhvX7KB7eVRXgq24GwLXDHSYCVMqCDEBrTdYQn5n5MTVguY9tsFI8ZbQM4T4dbQ2')
# Free stock photos for blog articles — get a free key at pexels.com/api
PEXELS_API_KEY = os.environ.get('PEXELS_API_KEY', 'GPlKuBUuXNxu06VvSJIM4pCSUGtHBwp3NwT7Q0XfFWgL2dwGB7yMTRqP')
# Serper.dev — Google image search for blog articles (2,500 free/month)
SERPER_API_KEY = os.environ.get('SERPER_API_KEY', 'f099f725535455f20dd5a70ca6f817ddc3dc76e5')

# ── Facebook Page integration ────────────────────────────────────────────────
# ── Site URL ─────────────────────────────────────────────────────────────────
SITE_URL = os.environ.get('SITE_URL', 'https://kbeatsradio.co.uk')

# ── Facebook ─────────────────────────────────────────────────────────────────
# Required permissions: pages_manage_posts, pages_read_engagement
FACEBOOK_PAGE_ID = os.environ.get('FACEBOOK_PAGE_ID', '966171646586881')
FACEBOOK_PAGE_ACCESS_TOKEN = os.environ.get('FACEBOOK_PAGE_ACCESS_TOKEN', 'EAAUVcMgjdSoBQ0nyoLLbQTB7i3mrOIleDSuUZCcfL3Y2eEZAHzSnjKnLOeUreOxBtsDv8Wh52T4fgIfpZAn5vKEfVb7bvZC3xmBxTSjZCLXBv79sd0qibQxcNwBVyah8c08UKeyhpDbAClAbB3D0Xy2aNBqmyvUg80Ew811zlHXoYZCVvLlrCSZBfRI9DMbvOUnS2uV6QZDZD')

# ── Instagram ─────────────────────────────────────────────────────────────────
# Instagram Business account must be linked to your Facebook Page.
# Uses the same Facebook Page Access Token above — no extra token needed.
# Set INSTAGRAM_POST_ENABLED=true to activate.
INSTAGRAM_POST_ENABLED = os.environ.get('INSTAGRAM_POST_ENABLED', 'false').lower() == 'true'

# ── X (Twitter) ───────────────────────────────────────────────────────────────
# Get from developer.twitter.com → Your App → Keys and Tokens
# Needs "Read and Write" OAuth 1.0a permissions.
X_API_KEY = os.environ.get('X_API_KEY', '')
X_API_SECRET = os.environ.get('X_API_SECRET', '')
X_ACCESS_TOKEN = os.environ.get('X_ACCESS_TOKEN', '')
X_ACCESS_TOKEN_SECRET = os.environ.get('X_ACCESS_TOKEN_SECRET', '')

# ── Pinterest ─────────────────────────────────────────────────────────────────
# Get from developers.pinterest.com → My Apps → your app → Access Token
# Board ID: open a board on Pinterest, copy the number from the URL.
PINTEREST_ACCESS_TOKEN = os.environ.get('PINTEREST_ACCESS_TOKEN', '')
PINTEREST_BOARD_ID = os.environ.get('PINTEREST_BOARD_ID', '')

# ── Cloudinary (image CDN) ───────────────────────────────────────────────────
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', 'diuanqnce')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '285831974678743')

# ── Backblaze B2 (Audio Storage) ─────────────────────────────────────────────
B2_KEY_ID = os.environ.get('B2_KEY_ID', 'a2e0a74c71c2')
B2_APPLICATION_KEY = os.environ.get('B2_APPLICATION_KEY', '003aca1366ecec133a01a611e2b26259e958c10129')
B2_BUCKET_NAME = os.environ.get('B2_BUCKET_NAME', 'StrayKids')
B2_DOWNLOAD_URL = os.environ.get('B2_DOWNLOAD_URL', 'https://f003.backblazeb2.com')
